use_frameworks!

platform :ios, '8.0'

target 'ChopeShopCommerce_Example' do
  pod 'ChopeShopCommerce', :path => '../'

  target 'ChopeShopCommerce_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
